### Get all decks
GET http://localhost:3000/api/decks/all

### Create a New Deck (Use userId from your local database)
POST http://localhost:3000/api/decks/create
Content-Type: application/json

{
  "userId": "b71c5377-7373-491f-9c2d-9a13dfb7b84f",
  "name": "Hola Vocabulary"
}

### Get unfinished deck for a specific user
GET http://localhost:3000/api/decks/get-unfinished-deck?userId=b71c5377-7373-491f-9c2d-9a13dfb7b84f
Content-Type: application/json

### Get individual deck by id
GET http://localhost:3000/api/decks/deck/1?userId=b71c5377-7373-491f-9c2d-9a13dfb7b84f