### Get all decks
GET http://localhost:3000/api/decks/all
Authorization: Bearer 'TOKEN'

### Create a New Deck (Use userId from your local database)
POST http://localhost:3000/api/decks/create
Content-Type: application/json

{
  "userId": "a4ec2f47-dfaa-44cc-8124-2ce595a7d562",
  "name": "Hola Vocabulary"
}

### Get unfinished deck for a specific user
GET http://localhost:3000/api/decks/get-unfinished-deck?userId=a4ec2f47-dfaa-44cc-8124-2ce595a7d562
Content-Type: application/json

### Get individual deck by id
GET http://localhost:3000/api/decks/deck/1

### Set deck to finished state 
PUT http://localhost:3000/api/decks/set-finished-deck/:deckId
